name: learn github workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up mise (Python + Poetry)
        uses: jdx/mise-action@v2

      - name: Install dependencies
        run: mise run install

      - name: Run app
        run: mise run run
